/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface EmailVerifications {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  hashed_token: string;
  user_id: string;
}

export interface OutboxMessages {
  available_at: Timestamp;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  last_error: string | null;
  locked_until: Timestamp | null;
  payload: string;
  processed_at: Timestamp | null;
  type: string;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  hashed_token: string;
  id: Generated<string>;
  user_id: string;
}

export interface Users {
  email: string;
  email_verified_at: Timestamp | null;
  id: Generated<string>;
  name: string;
  password: string;
  provider: Generated<string | null>;
}

export interface DB {
  email_verifications: EmailVerifications;
  outbox_messages: OutboxMessages;
  sessions: Sessions;
  users: Users;
}
